# Title: Even Fibonacci numbers
# Problem Statement:
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

import math

prev1 = 1
prev2 = 2
temp = 0
total = prev2

while temp <= int(4 * math.pow(10, 6)):
	temp = prev1 + prev2
	prev1 = prev2
	prev2 = temp
	if temp % 2 == 0:
		total += temp
	else:
		pass
print total